### ISSUE TITLE
GError [TypeError]: Cannot read property 'isUser' of undefined

### ISSUE THREAD

**Issue by bung87** [wechaty/puppet-whatsapp#15]
hi, I've written a simple demo code, after scan qrcode, whatsapp app show am logined on Google Chrome (Mac OS). my demo program throw this error,  looks like it can't load my contact info. I'v try enable v2ray global mode and `export http_proxy=http://127.0.0.1:1087;export https_proxy=http://127.0.0.1:1087;` , is there any thing am missing , any help would be appreciate, Thanks!
version:  

"wechaty": "1.10.4",
"wechaty-puppet": "1.10.2",
"wechaty-puppet-whatsapp": "^1.10.4",  

demo code:  
``` ts
import { WechatyBuilder }   from 'wechaty'
import { PuppetWhatsapp } from 'wechaty-puppet-whatsapp'
import qrcodeTerminal from 'qrcode-terminal';

const puppet  = new PuppetWhatsapp()
const wechaty = WechatyBuilder.singleton({ puppet });

wechaty
  .on('scan',    (qrCode, _) => {
    console.log(qrCode)
    console.log('https://wechaty.js.org/qrcode/' + encodeURIComponent(qrCode));
    qrcodeTerminal.generate(qrCode, { small: true });
  })
  .on('login',   user => console.log(`User ${user} logged in`))
  .on('message', message => console.log(`Message: ${message}`))
  .on('ready', console.info)
  .on('error', console.error)
wechaty.start()

```
log: 

```
GError [TypeError]: Cannot read property 'isUser' of undefined
    at PuppetWhatsapp.contactRawPayloadParser (/Users/bung/js_works/xiaoju-bot/node_modules/wechaty-puppet-whatsapp/src/puppet-whatsapp.ts:254:25)
    at PuppetWhatsapp.contactPayload (/Users/bung/js_works/xiaoju-bot/node_modules/wechaty-puppet/src/mixins/contact-mixin.ts:299:37)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async WechatifiedUserClass.ready (/Users/bung/js_works/xiaoju-bot/node_modules/wechaty/src/user-modules/contact.ts:691:23)
    at async Function.find (/Users/bung/js_works/xiaoju-bot/node_modules/wechaty/src/user-modules/contact.ts:104:9)
    at async Function.find (/Users/bung/js_works/xiaoju-bot/node_modules/wechaty/src/user-modules/contact-self.ts:65:23)
    at async PuppetWhatsapp.<anonymous> (/Users/bung/js_works/xiaoju-bot/node_modules/wechaty/src/wechaty-mixins/puppet-mixin.ts:233:33) {
  code: 2,
  details: "TypeError: Cannot read property 'isUser' of undefined\n" +
    '    at PuppetWhatsapp.contactRawPayloadParser (/Users/bung/js_works/xiaoju-bot/node_modules/wechaty-puppet-whatsapp/src/puppet-whatsapp.ts:254:25)\n' +
    '    at PuppetWhatsapp.contactPayload (/Users/bung/js_works/xiaoju-bot/node_modules/wechaty-puppet/src/mixins/contact-mixin.ts:299:37)\n' +
    '    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n' +
    '    at async WechatifiedUserClass.ready (/Users/bung/js_works/xiaoju-bot/node_modules/wechaty/src/user-modules/contact.ts:691:23)\n' +
    '    at async Function.find (/Users/bung/js_works/xiaoju-bot/node_modules/wechaty/src/user-modules/contact.ts:104:9)\n' +
    '    at async Function.find (/Users/bung/js_works/xiaoju-bot/node_modules/wechaty/src/user-modules/contact-self.ts:65:23)\n' +
    '    at async PuppetWhatsapp.<anonymous> (/Users/bung/js_works/xiaoju-bot/node_modules/wechaty/src/wechaty-mixins/puppet-mixin.ts:233:33)'
}
```

**Comment by huan** [comment]
> export http_proxy=http://127.0.0.1:1087;export https_proxy=http://127.0.0.1:1087;

My suggestion is to try using a VPS in the US instead.

**Comment by bung87** [comment]
It's probably not network condition, I even received a message from my friend before it throw error.
