### ISSUE TITLE
Session closed. Most likely the page has been closed.

### ISSUE THREAD

**Issue by su-chang** [wechaty/puppet-whatsapp#237]
```
22:30:00 ERR Config ###########################
22:30:00 ERR Config unhandledRejection: Error: Protocol error (Runtime.callFunctionOn): Session closed. Most likely the page has been closed.
    at CDPSession.send (/xiaoju-bot/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:218:35)
    at ExecutionContext._evaluateInternal (/xiaoju-bot/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:204:50)
    at ExecutionContext.evaluate (/xiaoju-bot/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:110:27)
    at DOMWorld.evaluate (/xiaoju-bot/node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:95:24) [object Promise]
22:30:00 ERR Config ###########################
22:30:00 ERR Config ###########################
22:30:00 ERR Config unhandledRejection: Error: Protocol error (Runtime.callFunctionOn): Session closed. Most likely the page has been closed. [object Promise]
22:30:00 ERR Config ###########################
22:30:00 ERR Config process.on(unhandledRejection) promise.catch(Protocol error (Runtime.callFunctionOn): Session closed. Most likely the page has been closed.)
Config Error: Protocol error (Runtime.callFunctionOn): Session closed. Most likely the page has been closed.
    at CDPSession.send (/xiaoju-bot/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:218:35)
    at ExecutionContext._evaluateInternal (/xiaoju-bot/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:204:50)
    at ExecutionContext.evaluate (/xiaoju-bot/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:110:27)
    at DOMWorld.evaluate (/xiaoju-bot/node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:95:24)
22:30:00 ERR Config process.on(unhandledRejection) promise.catch(Protocol error (Runtime.callFunctionOn): Session closed. Most likely the page has been closed.)
Config Error: Protocol error (Runtime.callFunctionOn): Session closed. Most likely the page has been closed.
    at CDPSession.send (/xiaoju-bot/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:218:35)
    at ExecutionContext._evaluateInternal (/xiaoju-bot/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:204:50)
    at ExecutionContext.evaluate (/xiaoju-bot/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:110:27)
    at DOMWorld.evaluate (/xiaoju-bot/node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:95:24)
(node:10) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 28)
22:30:01 INFO BotAction syncContact(ready=false, forceSync=false)
```

**Comment by su-chang** [comment]
```
22:45:30 VERB Contact say(FileBox#Url<1M.xls>)
22:45:30 INFO PuppetWhatsApp message messageSendFile(8613811387682@c.us, 1M.xls)
22:45:32 INFO PuppetWhatsApp message messageSend(8613811387682@c.us, object)
22:45:32 ERR BroadcastTaskWorker _sendTask(620e5f88598a57ecccad1dbd) error:
Error: Protocol error (Runtime.callFunctionOn): Session closed. Most likely the page has been closed.
    at CDPSession.send (/xiaoju-bot/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:218:35)
    at ExecutionContext._evaluateInternal (/xiaoju-bot/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:204:50)
    at ExecutionContext.evaluate (/xiaoju-bot/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:110:27)
    at DOMWorld.evaluate (/xiaoju-bot/node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:95:24)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by bung87** [comment]
unhandledRejection 在 puppet-whatsapp 或者manager那儿监听 Protocol error (Runtime.callFunctionOn): Session closed 的时候重启。
