### ISSUE TITLE
Login issue

### ISSUE THREAD

**Issue by hcfw007** [wechaty/puppet-whatsapp#372]
Sometimes we cannot login after scan:
```
18:26:59 VERB WhatsAppManager start() whatsapp.initialize() done.
18:26:59 ERR Config ###########################
18:26:59 ERR Config Wechaty unhandledRejection: Error: Evaluation failed: TypeError: Cannot read property 'map' of undefined
    at Object.window.WWebJS.getContacts (__puppeteer_evaluation_script__:381:25)
    at __puppeteer_evaluation_script__:2:34
    at ExecutionContext._evaluateInternal (/xiaoju-bot/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:221:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async ExecutionContext.evaluate (/xiaoju-bot/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:110:16)
    at async Client.getContacts (/xiaoju-bot/node_modules/@juzi/whatsapp-web.js/src/Client.js:673:24)
    at async Manager.syncContactOrRoomList (/xiaoju-bot/node_modules/wechaty-puppet-whatsapp/dist/cjs/src/manager.js:171:29)
    at async LoginEventHandler.onWhatsAppReady (/xiaoju-bot/node_modules/wechaty-puppet-whatsapp/dist/cjs/src/whatsapp/event-handler/login-event-handler.js:55:35) [object Promise]
18:26:59 ERR Config ###########################
18:26:59 ERR Config ###########################
18:26:59 ERR Config unhandledRejection: Error: Evaluation failed: TypeError: Cannot read property 'map' of undefined
    at Object.window.WWebJS.getContacts (__puppeteer_evaluation_script__:381:25)
    at __puppeteer_evaluation_script__:2:34 [object Promise]
18:26:59 ERR Config ###########################
18:26:59 ERR Config process.on(unhandledRejection) promise.catch(Evaluation failed: TypeError: Cannot read property 'map' of undefined
    at Object.window.WWebJS.getContacts (__puppeteer_evaluation_script__:381:25)
    at __puppeteer_evaluation_script__:2:34)
Config Error: Evaluation failed: TypeError: Cannot read property 'map' of undefined
    at Object.window.WWebJS.getContacts (__puppeteer_evaluation_script__:381:25)
    at __puppeteer_evaluation_script__:2:34
    at ExecutionContext._evaluateInternal (/xiaoju-bot/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:221:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async ExecutionContext.evaluate (/xiaoju-bot/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:110:16)
    at async Client.getContacts (/xiaoju-bot/node_modules/@juzi/whatsapp-web.js/src/Client.js:673:24)
    at async Manager.syncContactOrRoomList (/xiaoju-bot/node_modules/wechaty-puppet-whatsapp/dist/cjs/src/manager.js:171:29)
    at async LoginEventHandler.onWhatsAppReady (/xiaoju-bot/node_modules/wechaty-puppet-whatsapp/dist/cjs/src/whatsapp/event-handler/login-event-handler.js:55:35)
18:26:59 ERR Config process.on(unhandledRejection) promise.catch(Evaluation failed: TypeError: Cannot read property 'map' of undefined
    at Object.window.WWebJS.getContacts (__puppeteer_evaluation_script__:381:25)
    at __puppeteer_evaluation_script__:2:34)
Config Error: Evaluation failed: TypeError: Cannot read property 'map' of undefined
    at Object.window.WWebJS.getContacts (__puppeteer_evaluation_script__:381:25)
    at __puppeteer_evaluation_script__:2:34
    at ExecutionContext._evaluateInternal (/xiaoju-bot/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:221:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async ExecutionContext.evaluate (/xiaoju-bot/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:110:16)
    at async Client.getContacts (/xiaoju-bot/node_modules/@juzi/whatsapp-web.js/src/Client.js:673:24)
    at async Manager.syncContactOrRoomList (/xiaoju-bot/node_modules/wechaty-puppet-whatsapp/dist/cjs/src/manager.js:171:29)
    at async LoginEventHandler.onWhatsAppReady (/xiaoju-bot/node_modules/wechaty-puppet-whatsapp/dist/cjs/src/whatsapp/event-handler/login-event-handler.js:55:35)
(node:9) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 1)
```

**Comment by hcfw007** [comment]
#375
