### ISSUE TITLE
Can not login success after scan qrcode.

### ISSUE THREAD

**Issue by su-chang** [wechaty/puppet-whatsapp#374]
```
13:43:46 INFO [2] Scan QR Code above url to log in:
13:44:00 INFO LoginEventHandler onAuthenticated()
13:44:00 INFO WhatsAppManager initWhatsAppEvents: "authenticated", value: undefined
13:44:00 INFO WhatsAppManager initWhatsAppEvents: "ready", value: undefined
13:44:00 ERR Config ###########################
13:44:00 ERR Config unhandledRejection: Error: Evaluation failed: TypeError: Cannot read property 'map' of undefined
    at Object.window.WWebJS.getContacts (__puppeteer_evaluation_script__:381:25)
    at __puppeteer_evaluation_script__:2:34 [object Promise]
13:44:00 ERR Config ###########################
13:44:00 ERR Config process.on(unhandledRejection) promise.catch(Evaluation failed: TypeError: Cannot read property 'map' of undefined
    at Object.window.WWebJS.getContacts (__puppeteer_evaluation_script__:381:25)
    at __puppeteer_evaluation_script__:2:34)
Config Error: Evaluation failed: TypeError: Cannot read property 'map' of undefined
    at Object.window.WWebJS.getContacts (__puppeteer_evaluation_script__:381:25)
    at __puppeteer_evaluation_script__:2:34
    at ExecutionContext._evaluateInternal (/xiaoju-bot/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:221:19)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async ExecutionContext.evaluate (/xiaoju-bot/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:110:16)
    at async Client.getContacts (/xiaoju-bot/node_modules/@juzi/whatsapp-web.js/src/Client.js:673:24)
    at async Manager.syncContactOrRoomList (/xiaoju-bot/node_modules/wechaty-puppet-whatsapp/dist/cjs/src/manager.js:171:29)
    at async LoginEventHandler.onWhatsAppReady (/xiaoju-bot/node_modules/wechaty-puppet-whatsapp/dist/cjs/src/whatsapp/event-handler/login-event-handler.js:55:35)
(node:10) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 1)
13:44:01 INFO GroupEventHandler onRoomUpdate({"id":{"fromMe":false,"remote":"120363020899940021@g.us","id":"3EB050A7489C076D7A37","_serialized":"false_120363020899940021@g.us_3EB050A7489C076D7A37"},"body":"","type":"initial_pHash_mismatch","timestamp":1654753440,"chatId":"120363020899940021@g.us","recipientIds":[]})
```

Related comment: https://github.com/pedroslopez/whatsapp-web.js/issues/1492#issuecomment-1148212987

**Comment by hcfw007** [comment]
same with #372
