### ISSUE TITLE
发送图片后未收到匹配的回调事件，导致请求响应超时。

### ISSUE THREAD

**Issue by su-chang** [wechaty/puppet-whatsapp#381]
### 现象
1. 发送图片转圈
2. 接收到来自手机的图片
3. 3分钟后，提示发送失败

### 日志

```log
10:04:27 INFO Message Listener {"_events":{},"_eventsCount":0,"id":"3EB091836119B194FC5C","payload":{"fromId":"8613126768525@c.us","talkerId":"8613126768525@c.us","id":"3EB091836119B194FC5C","mentionIdList":[],"text":"","timestamp":1655258667,"toId":"8613811254048@c.us","listenerId":"8613811254048@c.us","type":6}}
10:04:27 INFO saveMessageListener Save Message Listener {"_events":{},"_eventsCount":0,"id":"3EB091836119B194FC5C","payload":{"fromId":"8613126768525@c.us","talkerId":"8613126768525@c.us","id":"3EB091836119B194FC5C","mentionIdList":[],"text":"","timestamp":1655258667,"toId":"8613811254048@c.us","listenerId":"8613811254048@c.us","type":6}}
10:04:30 INFO saveMessageListener Parse messageModel {"messageId":"3EB091836119B194FC5C","botId":"6247096354b7351f4df5aa78","groupId":"623004ff11dae09896b6dbed","orgId":"5c6938ab0bdf005a5239150b","fromId":"8613126768525@c.us","fromName":"苏畅","targetId":"8613811254048@c.us","targetName":"8613811254048@c.us","targetType":"Contact","avatar":"https://pps.whatsapp.net/v/t61.24694-24/181087133_415493120369760_5400600908885704928_n.jpg?ccb=11-4&oh=01_AVypS5s8lG8NddvYDaSBfxIsNWQxZa76lcjfuxVmCGW2Tw&oe=62B67AA2","type":"Image","channel":"Phone","timestamp":1655258667739,"snapshotDay":"2022-06-15","self":true,"mentionSelf":false,"coworker":false,"payload":{"url":"https://s3.cn-northwest-1.amazonaws.com.cn/xiaoju-message-payload-bucket/message/6247096354b7351f4df5aa78/1655258668911/unknown_name.jpeg","size":165405}}
10:06:54 ERR consumption message got error: Error: consumption message timeout msg: {"type":"sendMessage","messageBody":{"clientId":"5f964aa92197f0010faa9aa7-1655258662326","sendBy":"5f964aa92197f0010faa9aa7","to":{"type":0,"contactOrRoomId":"8613811254048@c.us","chatId":"628c6f8da6d088ee9d81e21b"},"body":{"message":{"messageType":1,"messageContent":{"url":"https://s3.cn-north-1.amazonaws.com.cn/xiaoju-material/public/5f964aa92197f0010faa9aa7_1655258662326_img1.png","size":1025284,"name":"img1.png"}}}}} msg: {"type":"sendMessage","messageBody":{"clientId":"5f964aa92197f0010faa9aa7-1655258662326","sendBy":"5f964aa92197f0010faa9aa7","to":{"type":0,"contactOrRoomId":"8613811254048@c.us","chatId":"628c6f8da6d088ee9d81e21b"},"body":{"message":{"messageType":1,"messageContent":{"url":"https://s3.cn-north-1.amazonaws.com.cn/xiaoju-material/public/5f964aa92197f0010faa9aa7_1655258662326_img1.png","size":1025284,"name":"img1.png"}}}}}
10:07:22 ERR consumption message got error: Error: consumption message timeout msg: {"type":"sendMessage","messageBody":{"clientId":"5f964aa92197f0010faa9aa7-1655258691750","sendBy":"5f964aa92197f0010faa9aa7","to":{"type":0,"contactOrRoomId":"8613811254048@c.us","chatId":"628c6f8da6d088ee9d81e21b"},"body":{"message":{"messageType":1,"messageContent":{"url":"https://s3.cn-north-1.amazonaws.com.cn/xiaoju-material/public/5f964aa92197f0010faa9aa7_1655258691750_59af83f5-af0d-4cdb-8b83-78de40249b6b_image.png","size":32568,"name":"image.png"}}}}} msg: {"type":"sendMessage","messageBody":{"clientId":"5f964aa92197f0010faa9aa7-1655258691750","sendBy":"5f964aa92197f0010faa9aa7","to":{"type":0,"contactOrRoomId":"8613811254048@c.us","chatId":"628c6f8da6d088ee9d81e21b"},"body":{"message":{"messageType":1,"messageContent":{"url":"https://s3.cn-north-1.amazonaws.com.cn/xiaoju-material/public/5f964aa92197f0010faa9aa7_1655258691750_59af83f5-af0d-4cdb-8b83-78de40249b6b_image.png","size":32568,"name":"image.png"}}}}}
10:14:22 ERR messageService Error: GrpcOrgService getOrg catch error: Error: 14 UNAVAILABLE: read ECONNRESET
    at Object.callErrorFromStatus (/xiaoju-bot/node_modules/@grpc/grpc-js/build/src/call.js:31:26)
    at Object.onReceiveStatus (/xiaoju-bot/node_modules/@grpc/grpc-js/build/src/client.js:189:52)
    at Object.onReceiveStatus (/xiaoju-bot/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:365:141)
    at Object.onReceiveStatus (/xiaoju-bot/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:328:181)
    at /xiaoju-bot/node_modules/@grpc/grpc-js/build/src/call-stream.js:187:78
    at processTicksAndRejections (node:internal/process/task_queues:78:11)
10:16:50 ERR consumption message got error: Error: consumption message timeout msg: {"type":"sendMessage","messageBody":{"clientId":"5f964aa92197f0010faa9aa7-1655259259799","sendBy":"5f964aa92197f0010faa9aa7","to":{"type":0,"contactOrRoomId":"8613811254048@c.us","chatId":"628c6f8da6d088ee9d81e21b"},"body":{"message":{"messageType":1,"messageContent":{"url":"https://s3.cn-north-1.amazonaws.com.cn/xiaoju-material/public/5f964aa92197f0010faa9aa7_1655259259799_72354af8-7c24-4653-84bc-c52abcd814dd_image.png","size":22292,"name":"image.png"}}}}} msg: {"type":"sendMessage","messageBody":{"clientId":"5f964aa92197f0010faa9aa7-1655259259799","sendBy":"5f964aa92197f0010faa9aa7","to":{"type":0,"contactOrRoomId":"8613811254048@c.us","chatId":"628c6f8da6d088ee9d81e21b"},"body":{"message":{"messageType":1,"messageContent":{"url":"https://s3.cn-north-1.amazonaws.com.cn/xiaoju-material/public/5f964aa92197f0010faa9aa7_1655259259799_72354af8-7c24-4653-84bc-c52abcd814dd_image.png","size":22292,"name":"image.png"}}}}}
10:17:56 ERR consumption message got error: Error: consumption message timeout msg: {"type":"sendMessage","messageBody":{"clientId":"5f964aa92197f0010faa9aa7-1655259326391","sendBy":"5f964aa92197f0010faa9aa7","to":{"type":0,"contactOrRoomId":"8613811254048@c.us","chatId":"628c6f8da6d088ee9d81e21b"},"body":{"message":{"messageType":1,"messageContent":{"url":"https://s3.cn-north-1.amazonaws.com.cn/xiaoju-material/public/5f964aa92197f0010faa9aa7_1655259326391_6b8f631c-b4c8-4cc4-8981-d2b685dbecbe_image.png","size":30342,"name":"image.png"}}}}} msg: {"type":"sendMessage","messageBody":{"clientId":"5f964aa92197f0010faa9aa7-1655259326391","sendBy":"5f964aa92197f0010faa9aa7","to":{"type":0,"contactOrRoomId":"8613811254048@c.us","chatId":"628c6f8da6d088ee9d81e21b"},"body":{"message":{"messageType":1,"messageContent":{"url":"https://s3.cn-north-1.amazonaws.com.cn/xiaoju-material/public/5f964aa92197f0010faa9aa7_1655259326391_6b8f631c-b4c8-4cc4-8981-d2b685dbecbe_image.png","size":30342,"name":"image.png"}}}}}
10:19:27 ERR say not return message
10:19:27 ERR MessageSender sendMessage() new, failed, TIMEOUT when processing request :3EB091836119B194FC5C, formatError: {"code":101,"message":"系统错误，请重启后稍后重试","error":{"code":1101,"message":"TIMEOUT when processing request :3EB091836119B194FC5C","name":"ERR_REQUEST_TIMEOUT"}}
10:19:54 ERR say not return message
```

### 案例截图
**发送时的截图**
![image](https://user-images.githubusercontent.com/9332609/173723517-c0393b83-e369-48ea-89f8-5014db4fefff.png)

**提示发送失败的截图**
![image](https://user-images.githubusercontent.com/9332609/173723566-89711477-1ded-4581-b126-73fadec81391.png)

**Comment by su-chang** [comment]
Related PR: https://github.com/juzibot/wechaty-puppet-whatsapp/pull/9

**Comment by chenzhiqiang0518** [comment]
@su-chang 你是连接到whatsapp上的吗
